# Generated by Django 6.1 on 2026-08-26 17:12

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('url', models.URLField(max_length=500)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tbl_source',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Earthquake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_event_id', models.CharField(max_length=50)),
                ('event_date', models.DateTimeField()),
                ('usgs_updated_date', models.DateTimeField()),
                ('magnitude', models.DecimalField(decimal_places=2, max_digits=4)),
                ('magnitude_type', models.CharField(blank=True, max_length=20, null=True)),
                ('event_type', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('depth_km', models.DecimalField(decimal_places=3, max_digits=8)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('place', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('country_code', models.CharField(blank=True, max_length=10, null=True)),
                ('region', models.CharField(blank=True, max_length=150, null=True)),
                ('usgs_url', models.URLField(blank=True, max_length=500, null=True)),
                ('tsunami', models.BooleanField(default=False)),
                ('felt_reports', models.IntegerField(blank=True, null=True)),
                ('cdi', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('mmi', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('significance', models.IntegerField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='earthquakes', to='earthquakes.source')),
            ],
            options={
                'db_table': 'tbl_earthquake',
                'ordering': ['-event_date'],
                'indexes': [models.Index(fields=['event_date'], name='tbl_earthqu_event_d_ddd662_idx'), models.Index(fields=['magnitude'], name='tbl_earthqu_magnitu_51d22b_idx'), models.Index(fields=['status'], name='tbl_earthqu_status_c1a727_idx'), models.Index(fields=['source', 'source_event_id'], name='tbl_earthqu_source__6af502_idx')],
                'constraints': [models.UniqueConstraint(fields=('source', 'source_event_id'), name='uq_earthquake_source_event')],
            },
        ),
    ]
