# Generated by Django 6.1 on 2026-08-26 19:15

from django.db import migrations

### Mofified from
def seed_usgs_source(apps, schema_editor):
    Source = apps.get_model("earthquakes", "Source")

    Source.objects.create(
        code="USGS",
        name="United States Geological Survey",
        url="https://earthquake.usgs.gov/",
    )


def remove_usgs_source(apps, schema_editor):
    Source = apps.get_model("earthquakes", "Source")
    Source.objects.filter(code="USGS").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("earthquakes", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            seed_usgs_source,
            remove_usgs_source,
        ),
    ]