# Generated by Django 6.1 on 2026-08-28 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earthquakes', '0002_seed_usgs_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='earthquake',
            name='region_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
