[project]
name = "earthquake-map"
version = "0.1.0"
description = "Web application for visualizing earthquake data"
requires-python = ">=3.14"
dependencies = [
    "Django",
    "djangorestframework",
    "psycopg[binary]",
    "requests",
    "python-dateutil",
]

[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"